import { CURRENCY_META } from './currency';

export const PREDEFINED_ASSETS = [
  {
    id: 'gold-gram',
    name: 'Gram Altın',
    shortName: '995/1000',
    type: 'gold',
    unit: 'gram',
    coinGeckoId: null,
    metalKey: 'gold',
    color: '#F59E0B',
    emoji: '🥇',
  },
  {
    id: 'silver-gram',
    name: 'Gram Gümüş',
    shortName: '995/1000',
    type: 'silver',
    unit: 'gram',
    coinGeckoId: null,
    metalKey: 'silver',
    color: '#94A3B8',
    emoji: '🥈',
  },
  {
    id: 'gold-oz',
    name: 'Ons Altın',
    shortName: 'XAU',
    type: 'gold',
    unit: 'ons',
    coinGeckoId: null,
    metalKey: 'gold',
    color: '#F59E0B',
    emoji: '🥇',
  },
  {
    id: 'silver-oz',
    name: 'Ons Gümüş',
    shortName: 'XAG',
    type: 'silver',
    unit: 'ons',
    coinGeckoId: null,
    metalKey: 'silver',
    color: '#94A3B8',
    emoji: '🥈',
  },
  {
    id: 'btc',
    name: 'Bitcoin',
    shortName: 'BTC',
    type: 'crypto',
    unit: 'BTC',
    coinGeckoId: 'bitcoin',
    color: '#F7931A',
    emoji: '₿',
  },
  {
    id: 'eth',
    name: 'Ethereum',
    shortName: 'ETH',
    type: 'crypto',
    unit: 'ETH',
    coinGeckoId: 'ethereum',
    color: '#627EEA',
    emoji: '⬠',
  },
  {
    id: 'bnb',
    name: 'BNB',
    shortName: 'BNB',
    type: 'crypto',
    unit: 'BNB',
    coinGeckoId: 'binancecoin',
    color: '#F0B90B',
    emoji: '🔶',
  },
  {
    id: 'xrp',
    name: 'Ripple',
    shortName: 'XRP',
    type: 'crypto',
    unit: 'XRP',
    coinGeckoId: 'ripple',
    color: '#00AAE4',
    emoji: '💧',
  },
  {
    id: 'sol',
    name: 'Solana',
    shortName: 'SOL',
    type: 'crypto',
    unit: 'SOL',
    coinGeckoId: 'solana',
    color: '#9945FF',
    emoji: '◎',
  },
  {
    id: 'trx',
    name: 'Tron',
    shortName: 'TRX',
    type: 'crypto',
    unit: 'TRX',
    coinGeckoId: 'tron',
    color: '#EF0027',
    emoji: '△',
  },
  {
    id: 'ada',
    name: 'Cardano',
    shortName: 'ADA',
    type: 'crypto',
    unit: 'ADA',
    coinGeckoId: 'cardano',
    color: '#0033AD',
    emoji: '₳',
  },
  {
    id: 'xmr',
    name: 'Monero',
    shortName: 'XMR',
    type: 'crypto',
    unit: 'XMR',
    coinGeckoId: 'monero',
    color: '#FF6600',
    emoji: 'ɱ',
  },
  {
    id: 'xlm',
    name: 'Stellar',
    shortName: 'XLM',
    type: 'crypto',
    unit: 'XLM',
    coinGeckoId: 'stellar',
    color: '#14B6E7',
    emoji: '*',
  },
  {
    id: 'ltc',
    name: 'Litecoin',
    shortName: 'LTC',
    type: 'crypto',
    unit: 'LTC',
    coinGeckoId: 'litecoin',
    color: '#345D9D',
    emoji: 'Ł',
  },
  {
    id: 'avax',
    name: 'Avalanche',
    shortName: 'AVAX',
    type: 'crypto',
    unit: 'AVAX',
    coinGeckoId: 'avalanche-2',
    color: '#E84142',
    emoji: '▲',
  },
  {
    id: 'paxg',
    name: 'PAX Gold',
    shortName: 'PAXG',
    type: 'crypto',
    unit: 'PAXG',
    coinGeckoId: 'pax-gold',
    color: '#F0C040',
    emoji: '🟡',
  },
  {
    id: 'xaut',
    name: 'Tether Gold',
    shortName: 'XAUT',
    type: 'crypto',
    unit: 'XAUT',
    coinGeckoId: 'tether-gold',
    color: '#F0C040',
    emoji: '🟡',
  },
  {
    id: 'usd',
    name: 'Dolar',
    shortName: 'USD',
    type: 'forex',
    unit: 'USD',
    coinGeckoId: null,
    color: '#22C55E',
    emoji: '🇺🇸',
  },
  {
    id: 'eur',
    name: 'Euro',
    shortName: 'EUR',
    type: 'forex',
    unit: 'EUR',
    coinGeckoId: null,
    color: '#10B981',
    emoji: '🇪🇺',
  },
  {
    id: 'gbp',
    name: 'Sterlin',
    shortName: 'GBP',
    type: 'forex',
    unit: 'GBP',
    coinGeckoId: null,
    color: '#0F766E',
    emoji: '🇬🇧',
  },
  {
    id: 'jpy',
    name: 'Japon Yeni',
    shortName: 'JPY',
    type: 'forex',
    unit: 'JPY',
    coinGeckoId: null,
    color: '#DC2626',
    emoji: '🇯🇵',
  },
  {
    id: 'cny',
    name: 'Çin Yuanı',
    shortName: 'CNY',
    type: 'forex',
    unit: 'CNY',
    coinGeckoId: null,
    color: '#B91C1C',
    emoji: '🇨🇳',
  },
  {
    id: 'aud',
    name: 'Avustralya Doları',
    shortName: 'AUD',
    type: 'forex',
    unit: 'AUD',
    coinGeckoId: null,
    color: '#2563EB',
    emoji: '🇦🇺',
  },
  {
    id: 'cad',
    name: 'Kanada Doları',
    shortName: 'CAD',
    type: 'forex',
    unit: 'CAD',
    coinGeckoId: null,
    color: '#EF4444',
    emoji: '🇨🇦',
  },
  {
    id: 'chf',
    name: 'İsviçre Frangı',
    shortName: 'CHF',
    type: 'forex',
    unit: 'CHF',
    coinGeckoId: null,
    color: '#991B1B',
    emoji: '🇨🇭',
  },
  {
    id: 'hkd',
    name: 'Hong Kong Doları',
    shortName: 'HKD',
    type: 'forex',
    unit: 'HKD',
    coinGeckoId: null,
    color: '#E11D48',
    emoji: '🇭🇰',
  },
  {
    id: 'sgd',
    name: 'Singapur Doları',
    shortName: 'SGD',
    type: 'forex',
    unit: 'SGD',
    coinGeckoId: null,
    color: '#BE123C',
    emoji: '🇸🇬',
  },
  {
    id: 'inr',
    name: 'Hindistan Rupisi',
    shortName: 'INR',
    type: 'forex',
    unit: 'INR',
    coinGeckoId: null,
    color: '#EA580C',
    emoji: '🇮🇳',
  },
  {
    id: 'krw',
    name: 'Güney Kore Wonu',
    shortName: 'KRW',
    type: 'forex',
    unit: 'KRW',
    coinGeckoId: null,
    color: '#2563EB',
    emoji: '🇰🇷',
  },
  {
    id: 'sek',
    name: 'İsveç Kronu',
    shortName: 'SEK',
    type: 'forex',
    unit: 'SEK',
    coinGeckoId: null,
    color: '#0EA5E9',
    emoji: '🇸🇪',
  },
  {
    id: 'mxn',
    name: 'Meksika Pesosu',
    shortName: 'MXN',
    type: 'forex',
    unit: 'MXN',
    coinGeckoId: null,
    color: '#15803D',
    emoji: '🇲🇽',
  },
  {
    id: 'nzd',
    name: 'Yeni Zelanda Doları',
    shortName: 'NZD',
    type: 'forex',
    unit: 'NZD',
    coinGeckoId: null,
    color: '#1D4ED8',
    emoji: '🇳🇿',
  },
  {
    id: 'nok',
    name: 'Norveç Kronu',
    shortName: 'NOK',
    type: 'forex',
    unit: 'NOK',
    coinGeckoId: null,
    color: '#DC2626',
    emoji: '🇳🇴',
  },
  {
    id: 'twd',
    name: 'Yeni Tayvan Doları',
    shortName: 'TWD',
    type: 'forex',
    unit: 'TWD',
    coinGeckoId: null,
    color: '#0284C7',
    emoji: '🇹🇼',
  },
  {
    id: 'brl',
    name: 'Brezilya Reali',
    shortName: 'BRL',
    type: 'forex',
    unit: 'BRL',
    coinGeckoId: null,
    color: '#16A34A',
    emoji: '🇧🇷',
  },
  {
    id: 'zar',
    name: 'Güney Afrika Randı',
    shortName: 'ZAR',
    type: 'forex',
    unit: 'ZAR',
    coinGeckoId: null,
    color: '#0F766E',
    emoji: '🇿🇦',
  },
  {
    id: 'pln',
    name: 'Polonya Zlotisi',
    shortName: 'PLN',
    type: 'forex',
    unit: 'PLN',
    coinGeckoId: null,
    color: '#BE123C',
    emoji: '🇵🇱',
  },
  {
    id: 'try',
    name: 'Türk Lirası',
    shortName: 'TRY',
    type: 'forex',
    unit: 'TRY',
    coinGeckoId: null,
    color: '#16A34A',
    emoji: '🇹🇷',
  },
  {
    id: 'dkk',
    name: 'Danimarka Kronu',
    shortName: 'DKK',
    type: 'forex',
    unit: 'DKK',
    coinGeckoId: null,
    color: '#DC2626',
    emoji: '🇩🇰',
  },
  {
    id: 'czk',
    name: 'Çek Korunası',
    shortName: 'CZK',
    type: 'forex',
    unit: 'CZK',
    coinGeckoId: null,
    color: '#2563EB',
    emoji: '🇨🇿',
  },
  {
    id: 'huf',
    name: 'Macar Forinti',
    shortName: 'HUF',
    type: 'forex',
    unit: 'HUF',
    coinGeckoId: null,
    color: '#15803D',
    emoji: '🇭🇺',
  },
  {
    id: 'ron',
    name: 'Rumen Leyi',
    shortName: 'RON',
    type: 'forex',
    unit: 'RON',
    coinGeckoId: null,
    color: '#F59E0B',
    emoji: '🇷🇴',
  },
  {
    id: 'bgn',
    name: 'Bulgar Levası',
    shortName: 'BGN',
    type: 'forex',
    unit: 'BGN',
    coinGeckoId: null,
    color: '#16A34A',
    emoji: '🇧🇬',
  },
  {
    id: 'isk',
    name: 'İzlanda Kronu',
    shortName: 'ISK',
    type: 'forex',
    unit: 'ISK',
    coinGeckoId: null,
    color: '#1D4ED8',
    emoji: '🇮🇸',
  },
  {
    id: 'uah',
    name: 'Ukrayna Grivnası',
    shortName: 'UAH',
    type: 'forex',
    unit: 'UAH',
    coinGeckoId: null,
    color: '#EAB308',
    emoji: '🇺🇦',
  },
  {
    id: 'rsd',
    name: 'Sırp Dinarı',
    shortName: 'RSD',
    type: 'forex',
    unit: 'RSD',
    coinGeckoId: null,
    color: '#BE123C',
    emoji: '🇷🇸',
  },
  {
    id: 'all',
    name: 'Arnavutluk Leki',
    shortName: 'ALL',
    type: 'forex',
    unit: 'ALL',
    coinGeckoId: null,
    color: '#B91C1C',
    emoji: '🇦🇱',
  },
  {
    id: 'bam',
    name: 'Bosna-Hersek Markı',
    shortName: 'BAM',
    type: 'forex',
    unit: 'BAM',
    coinGeckoId: null,
    color: '#0EA5E9',
    emoji: '🇧🇦',
  },
  {
    id: 'mkd',
    name: 'Makedon Dinarı',
    shortName: 'MKD',
    type: 'forex',
    unit: 'MKD',
    coinGeckoId: null,
    color: '#DC2626',
    emoji: '🇲🇰',
  },
  {
    id: 'mdl',
    name: 'Moldova Leyi',
    shortName: 'MDL',
    type: 'forex',
    unit: 'MDL',
    coinGeckoId: null,
    color: '#2563EB',
    emoji: '🇲🇩',
  },
  {
    id: 'gel',
    name: 'Gürcistan Larisi',
    shortName: 'GEL',
    type: 'forex',
    unit: 'GEL',
    coinGeckoId: null,
    color: '#EF4444',
    emoji: '🇬🇪',
  },
  {
    id: 'amd',
    name: 'Ermeni Dramı',
    shortName: 'AMD',
    type: 'forex',
    unit: 'AMD',
    coinGeckoId: null,
    color: '#F97316',
    emoji: '🇦🇲',
  },
  {
    id: 'azn',
    name: 'Azerbaycan Manatı',
    shortName: 'AZN',
    type: 'forex',
    unit: 'AZN',
    coinGeckoId: null,
    color: '#0F766E',
    emoji: '🇦🇿',
  },
  {
    id: 'rub',
    name: 'Rus Rublesi',
    shortName: 'RUB',
    type: 'forex',
    unit: 'RUB',
    coinGeckoId: null,
    color: '#1E40AF',
    emoji: '🇷🇺',
  },
  {
    id: 'byn',
    name: 'Belarus Rublesi',
    shortName: 'BYN',
    type: 'forex',
    unit: 'BYN',
    coinGeckoId: null,
    color: '#16A34A',
    emoji: '🇧🇾',
  },
  {
    id: 'custom',
    name: 'Diğer',
    shortName: 'Özel',
    type: 'other',
    unit: 'adet',
    coinGeckoId: null,
    color: '#8B5CF6',
    emoji: '📦',
  },
];

export const TROY_OZ_TO_GRAM = 31.1034768;

export const getAssetById = (id) => {
  return PREDEFINED_ASSETS.find((a) => a.id === id) || null;
};

export const getLocalizedAssetName = (assetId, language = 'tr') => {
  const currencyCode = typeof assetId === 'string' ? assetId.toUpperCase() : '';
  const currencyMeta = CURRENCY_META[currencyCode];

  if (currencyMeta) {
    return language === 'en' ? currencyMeta.name : currencyMeta.localName;
  }

  const names = {
    'gold-gram': { tr: 'Gram Altın', en: 'Gram Gold' },
    'silver-gram': { tr: 'Gram Gümüş', en: 'Gram Silver' },
    'gold-oz': { tr: 'Ons Altın', en: 'Gold Ounce' },
    'silver-oz': { tr: 'Ons Gümüş', en: 'Silver Ounce' },
    btc: { tr: 'Bitcoin', en: 'Bitcoin' },
    bnb: { tr: 'BNB', en: 'BNB' },
    xrp: { tr: 'Ripple', en: 'Ripple' },
    eth: { tr: 'Ethereum', en: 'Ethereum' },
    sol: { tr: 'Solana', en: 'Solana' },
    trx: { tr: 'Tron', en: 'Tron' },
    ada: { tr: 'Cardano', en: 'Cardano' },
    xmr: { tr: 'Monero', en: 'Monero' },
    xlm: { tr: 'Stellar', en: 'Stellar' },
    ltc: { tr: 'Litecoin', en: 'Litecoin' },
    avax: { tr: 'Avalanche', en: 'Avalanche' },
    paxg: { tr: 'PAX Gold', en: 'PAX Gold' },
    xaut: { tr: 'Tether Gold', en: 'Tether Gold' },
    custom: { tr: 'Diğer', en: 'Other' },
  };

  return names[assetId]?.[language] || names[assetId]?.tr || getAssetById(assetId)?.name || assetId;
};

export const getAssetColor = (assetId) => {
  const asset = getAssetById(assetId);
  return asset ? asset.color : '#22C55E';
};

export const getAssetEmoji = (assetId) => {
  const asset = getAssetById(assetId);
  return asset ? asset.emoji : '📊';
};

export const ASSET_TYPES = [
  { key: 'all', label: 'Tümü' },
  { key: 'crypto', label: 'Kripto' },
  { key: 'gold', label: 'Altın' },
  { key: 'silver', label: 'Gümüş' },
  { key: 'forex', label: 'Döviz' },
  { key: 'other', label: 'Diğer' },
];
